name = "gustoflow-restaurant-mgmt"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "gustoflow-db"
database_id = "2898e41d-86db-472b-bd7d-998d95bc8b17"